### ISSUE TITLE
Make task state a choice option for pulp task list

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-cli#115]
`pulp task list --state nonexistent`

**Comment by thmo** [comment]
This has already been implemented as part of #82, see [this line](https://github.com/pulp/pulp-cli/blob/98728c73e93d390f8377dc1694d0aebadcc8bdad/pulpcore/cli/core/task.py#L28).

**Comment by mdellweg** [comment]
@thmo The issue here is, that you can specify anything for the state (like `nonexistent`). So the idea is to transform the existing option to be a choice option, and perform prevalidation before calling the api with a state that will only result in an empty list instead of raising an error to the user.
The real problem here are typos that give the wrong impression like:
`pulp task list --state rumming`

**Comment by mdellweg** [comment]
I thought it might be nice to have that validation in core, too:
https://github.com/pulp/pulpcore/pull/1133
